export enum PlaySelector {
    TimeStamp = "$ts",
    Username = "$username",
    Platform = "$platform",
    MsPlayed = "$ms_played",
    ConnCountry = "$conn_country",
    IPAddress = "$ip_addr_decrypted",
    UserAgent = "$user_agent_decrypted",
    TrackName = "$master_metadata_track_name",
    ArtistName = "$master_metadata_album_artist_name",
    AlbumName = "$master_metadata_album_album_name",
    TrackUri = "$spotify_track_uri",
    EpisodeName = "$episode_name",
    EpisodeShowName = "$episode_show_name",
    EpisodeUri = "$spotify_episode_uri",
    ReasonStart = "$reason_start",
    ReasonEnd = "$reason_end",
    Shuffle = "$shuffle",
    Skipped = "$skipped",
    Offline = "$offline",
    OfflineTimestamp = "$offline_timestamp",
    IncognitoMode = "$incognito_mode"
}